# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-target-blank
  - jekyll-seo-tag

# Site settings
title: "Soham Dongargaonkar"
description: > # this means to ignore newlines until "email:"
   My personal website where I blog about (mostly) software development

email: sohamssd@gmail.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/todo-please-add-image-here.jpg"

name: 'Soham Dongargaonkar'
author: 'Soham Dongargaonkar'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://a3y3.dev" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@sohamssd'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/sohamssd
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/a3y3
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
